### ISSUE TITLE
Demo

### ISSUE THREAD

**Issue by timsamuelsson** [SocialbitGmbH/BootstrapCarouselPageMerger#2]
Hi,

Your plugin looks awesome!

Could you add a jsfiddle? I cant get it working correctly and Im think Im missing some thing...

//Tim

**Comment by nikki22** [comment]
Yes please, a jsfiddle would be so helpful. I'm also struggling to get it to work.

thanks
Nikki

**Comment by blaues0cke** [comment]
Sorry, did not got a notification for that, will set up a demo right now.

**Comment by blaues0cke** [comment]
There you go: http://socialbitgmbh.github.io/BootstrapCarouselPageMerger/
